#!/usr/bin/env bash
# Created by ArieSR91
user="$(whoami)"

function vnc-help() {
    echo -e "
type:

vnc passwd = to set vnc password
vnc start = to start vnc client
vnc stop = to stop vnc client
"
    return 0
}

function passwd-vnc() {
    vncpasswd
    return 0
}

function stop-vnc() {
    vncserver -kill :1
    vncserver -kill :2
    rm -rf /home/$user/.vnc/localhost:1.pid
    rm -rf /root/.vnc/localhost:1.pid
    rm -rf /tmp/.X1-lock
    rm -rf /tmp/.X11-unix/X1
    return 0
}

function start-vnc() {
    vncserver -kill :1
    vncserver -kill :2
    export USER=$user
    export HOME=/home/$user
    if [ "$EUID" -eq 0 ]; then
        export HOME=/root
    fi
    echo "
Example: 1280x720
         1508x720
"
    read -p 'Your screen resolution: ' resolution;
    vncserver -geometry $resolution
    # vncserver -geometry 1280x720
    sessions=$(vncserver -list | sed s/"TigerVNC"/"Kali Linux"/)
    if [[ $sessions == *"590"* ]]; then
        printf "${sessions}\n"
        printf "\nYou can use the bVNC for login to GUI.\n"
    fi
    return 0
}

case $1 in
    start)
        start-vnc
        ;;
    stop)
        stop-vnc
        ;;
    passwd)
        passwd-vnc
        ;;
    *)
        vnc-help
        ;;
esac
